cs3org/cs3apis

cs3/publicshareprovider/v0alpha/publicshareprovider.proto
docs/index.html
proto.lock

Context (transcript from gitter):
>is there a reason behind the API choice for public shares vs user shares when it comes to the Create[*]ShareRequest? Where user shares requires a ResourceInfo (https://github.com/cs3org/cs3apis/blob/master/cs3/usershareprovider/v0alpha/usershareprovider.proto#L90) Public Shares requires a ResourceId (https://github.com/cs3org/cs3apis/blob/master/cs3/publicshareprovider/v0alpha/publicshareprovider.proto#L83) which enforces types that implement the public share an extra stat call to fetch the resource info (and all the instrumentation around it, i.e dependency injection)
and [a trip through git history](https://github.com/refs/cs3apis/commit/3dce4dc800e040296dd37d1d7f626ee5806c5d6b#diff-41199556adedb9d2eb022e74989713a7)
It seems this argument needs to be …

use resource_info instead of resource_id on CreatePublicShare

---

cs3/ocm/core/v1beta1/ocm_core_api.proto
cs3/sharing/ocm/v1beta1/ocm_api.proto
docs/index.html

When the user calls CreateOCMShare from OCS, we need to pass the endpoint of the recipient user's provider to the GRPC method, since the package will make a call to /ocm/shares at that endpoint.

Add recipient_mesh_provider field to CreateOCMShare

---

cs3/app/provider/v1beta1/provider_api.proto
docs/index.html

~~Following discussions with @ishank011, this extension of the OpenInAppProvider request/workflow allows to specify a `storage_id`.~~
Following further discussions, this is to better document how is this workflow expected to work - no changes to the protobuf.

Improvements in the OpenInAppProviderRequest docs

---

cs3/app/provider/v1beta1/provider_api.proto
cs3/gateway/v1beta1/gateway_api.proto
docs/index.html
proto.lock

This PR is a breaking change to split the external (gateway) protocol from the appprovider one.
The external one does not require the user token, whereas the internal appprovider one includes now a `ResourceInfo` instead of a `Reference` and the access token.

OpenFileInAppProvider enhancements

---

cs3/sharing/ocm/v1beta1/resources.proto
docs/index.html
proto.lock

Since we only store the ResourceID in OCM shares, there's no way to retrieve the resource name later. Currently we use a workaround where we append it with the share ID so that we can use it when creating references but that isn't ideal. This PR takes care of that.

Add name of the shared resource to OCM share

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/storage/provider/v1beta1/provider_api.proto

fixes https://github.com/cs3org/cs3apis/issues/88

storage provider: add CreateSymlink

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/tx/v1beta1/resources.proto
cs3/tx/v1beta1/tx_api.proto
docs/index.html

Some issues/questions:
- Protobuf does not like the term 'data' in a namespace, it gives an error: 
```
cs3/datatx/v1beta1/datatx_api.proto:21:1:The name "cs3.datatx.v1beta1" contains the outlawed name "data". Data is a decorator and all types on Protobuf are data, consider merging this information into a higher-level type, or if you must have such a type, Use "Info" instead..
```
I now have named it 'tx' to make it compile. Maybe 'dtx' or simply ‘transfer’ is more appropriate?
- In CreateTransferRequest the resource to be transferred is of type ResourceInfo. If this type is correct then maybe the ResourcePermissions should be expended with a 'transfer' permission.
- I’m not sure if additional fields like eg. ‘opaque’ info are needed in the methods.
- I have chosen to let all 3 methods …

New CS3 module tx (data transfer).

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/identity/group/v1beta1/group_api.proto
cs3/identity/group/v1beta1/resources.proto
cs3/identity/user/v1beta1/resources.proto
cs3/identity/user/v1beta1/user_api.proto
proto.lock

Signed-off-by: Jörn Friedrich Dreyer <jfd@butonic.de>
> This PR adds a readonly groups api to CS3.
Similar to users groups have a persistent, non reassignable, stable, unique identifier which we call id
In addition to that the CS3 API knows other identifiers like a name, an email and numeric identifiers (which we used to carry as opaque payload).
I did not care to preserve backwards compatability and reused old ids, which is why there are build failures for protobuf.
Let me know if we can go forward with this or if the API is considered staple and we need to keep backwards compatabililty.

Add Group API

---

cs3/storage/provider/v1beta1/resources.proto
docs/index.html
proto.lock

To enable group sharing, the grantee ID can be either a user ID or a group ID

Make the grantee ID either that of a user or a group

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/storage/provider/v1beta1/provider_api.proto
cs3/storage/provider/v1beta1/resources.proto
docs/index.html

Added a delete home method to the storage provider to be able to clean up when removing a user.

add delete home to the storage provider

---

cs3/ocm/invite/v1beta1/invite_api.proto
cs3/ocm/invite/v1beta1/resources.proto
docs/index.html

This PR adds a new rpc endpoint to fetch all users that accepted a certain InviteToken with a certain token name/label.
This requires that additional `name` field is also added by this PR to the `InviteToken` resource.
This field holds a user-definable token name, so that the user can later query for all users that accepted the token with this name.
Related [reva#1484](https://github.com/cs3org/reva/issues/1484)

Add GetAcceptedUsers to Invite api

---

cs3/ocm/invite/v1beta1/invite_api.proto
cs3/sharing/ocm/v1beta1/resources.proto
docs/index.html

It should be possible to persist the purpose of the share together with the share itself, so the application can act accordingly when eg. a received share is accepted. For this the `share_type` field is defined. 
Currently `SHARE` and `TRANSFER` share types are acknowledged.
See https://github.com/cs3org/reva/pull/1242#issuecomment-788932923.

Share type added to specify Share purpose.

---

cs3/storage/provider/v1beta1/resources.proto

The `RecycleItem` path should have a leading slash like other paths as well, but it was currently not specified to have it.

Clarify that the path has a leading slash in RecycleItem

---

cs3/storage/provider/v1beta1/resources.proto
docs/index.html

FileVersion must have an Etag property so that oCIS can provide them on the file versions endpoint (https://doc.owncloud.com/server/developer_manual/webdav_api/files_versions.html#file-is-found-and-has-multiple-versions).
Implementation WIP in Reva: https://github.com/cs3org/reva/pull/1526/commits/f2cadc43cf47c090dccbe35399393d78f19937f2

add etag to versions

---

cs3/sharing/link/v1beta1/link_api.proto
docs/index.html

For some alternative public share authentication methods we need to be able to access the public share password. Some more details are documented here: https://github.com/cs3org/cs3apis/issues/110

get public share methods also return the share password now

---

cs3/gateway/v1beta1/resources.proto
cs3/ocm/invite/v1beta1/resources.proto
cs3/storage/registry/v1beta1/registry_api.proto
docs/index.html
proto.lock

For cases where users are sharded across multiple storage providers, we need to match multiple such providers for a given reference and merge the results obtained from these. This is especially useful for listing, deleting sharded containers, etc.

Match multiple storage providers in registry

---

cs3/rpc/v1beta1/code.proto
docs/index.html

This PR adds the status code 507 Insufficient Storage to the CS3 apis. This status code is eg. needed for enforcing storage quotas.
Will be used by https://github.com/cs3org/reva/pull/1557

add status code 507

---

cs3/sharing/link/v1beta1/link_api.proto
cs3/sharing/link/v1beta1/resources.proto
docs/index.html
proto.lock

Deprecated the changes from https://github.com/cs3org/cs3apis/pull/113
and enhanced the api to support signature based authentication for
public links.

Support signature authentication for public links

---

cs3/app/provider/v1beta1/provider_api.proto
cs3/app/registry/v1beta1/registry_api.proto
docs/index.html

This will eventually supersede `OpenFileInAppProvider`.
The rationale being that `OpenInApp` generically refers to `ref`s, i.e. files AND directories, and a new optional parameter `app` was added, to allow:
1) In case of folders, to specify the app as the default logic to map mimetypes to apps cannot apply
2) In case of files, to allow overriding the default logic and support the case where the user asks to "Open with..." and multiple applications are registered for the same mimetype (typical case: `.docx` -> MS Office Online, OnlyOffice, Collabora Online).

Added a new OpenInApp request/response

---

cs3/sharing/collaboration/v1beta1/collaboration_api.proto
docs/index.html

Added the updated share to the UpdateShareResponse so that we don't have to do 2 requests to update and return the updated share.
This is similar to the CreateShareResponse.

update share api

---

cs3/auth/provider/v1beta1/provider_api.proto
cs3/auth/provider/v1beta1/resources.proto
docs/index.html

We mint the JWT tokens in Gateway/Authenticate. Adding an optional `token_scope` field would allow us to ensure that access is restricted to only these scopes. To be used in cases when we impersonate other users, including public shares, OCM shares and guest accounts.

Add token scope field to gateway authenticate requests

---

cs3/storage/provider/v1beta1/provider_api.proto
docs/index.html
proto.lock

This is a revamp of https://github.com/cs3org/cs3apis/pull/87, which got closed because the `master` branch got renamed to `main`...
Pasting here the relevant parts:
This extension is motivated by cs3org/wopiserver#25. Discussing with @ishank011 it looks reasonable to extend the `InitiateFileUploadRequest` to support exclusive operations: I may want to upload a file "no matter what", overwriting the destination - which is the current behavior. Or I may want to atomically check-and-upload, which is the scope of this new flag. Both actions are legitimate and should be supported.
The PR proposes a minimal extension of the protocol. May we need to support other POSIX(-like) flags and have rather an enum instead of just a bool? I guess by now we're settled, yet for reference the years-old …

Extend InitiateFileUpload to support exclusive uploads and etags-based checks

---

cs3/storage/provider/v1beta1/provider_api.proto
docs/index.html

Following #122, specifications are better spelled out now.

Documentation fixes

---

cs3/storage/provider/v1beta1/provider_api.proto
docs/index.html
proto.lock

Added a reference for the target resource on which the action should be executed. This is necessary because we want to be able to perform actions for specific resources in the recycle file tree and not only on the root of a deleted tree.
I started in https://github.com/cs3org/reva/pull/1827 to extend the recycle/trash-bin APIs in a way that actions can be performed for specific resources in the trash-bin file tree.
It works so far but the API needs some changes.
- `ListRecycle` and `ListRecycleStream` had neither a key nor a reference
- `RestoreRecycleItem` had a key and a ref 
This PR makes the Recycle API related methods consistent by adding a ref where missing and removing the key since it can be included in the reference and so we don't need to separate fields.

update the storageprovider recycle api

---

cs3/app/provider/v1beta1/provider_api.proto
cs3/app/registry/v1beta1/registry_api.proto
cs3/app/registry/v1beta1/resources.proto
cs3/gateway/v1beta1/gateway_api.proto
docs/index.html
proto.lock

This PR adds methods to register new app providers on the fly and to set and retrieve default app providers for mime types. It has a change that might break the clients using the current version. We remove the mime type filters from `ListAppProvidersRequest` as that is redundant and performs the same functionality as `GetAppProvidersRequest`.

Extend app registry with methods to add providers and mimetype filters

---

cs3/sharing/collaboration/v1beta1/collaboration_api.proto
cs3/sharing/collaboration/v1beta1/resources.proto
docs/index.html
proto.lock

We would like to filter the shares by grantee type i.e. We'd like to be able to list only user shares or only group shares.
This API change makes that possible to provide this filter to the storage provider.

add a filter for share grantee types

---

Makefile
cs3/app/provider/v1beta1/provider_api.proto
cs3/app/registry/v1beta1/registry_api.proto
cs3/app/registry/v1beta1/resources.proto
cs3/gateway/v1beta1/gateway_api.proto
docs/index.html
proto.lock

This PR introduces further extensions for the open-in-app workflow:
* `AppProvider`s expose a `capability` to identify fully fledged editors vs viewers
* Mime types are defined including a friendly name and a corresponding file extension
This allows the UI to e.g. populate a **New** menu with all types for which an `editor` AppProvider is defined.
The extensions constitute breaking changes for the protobuf bindings, and can be merged once cs3org/reva#2067 is ready to be merged.

Extensions for the AppProviders to improve the UI

---

cs3/sharing/collaboration/v1beta1/collaboration_api.proto
cs3/sharing/collaboration/v1beta1/resources.proto
cs3/sharing/ocm/v1beta1/ocm_api.proto
cs3/sharing/ocm/v1beta1/resources.proto
docs/index.html
proto.lock
prototool.yaml
third_party/google/protobuf/field_mask.proto
tools/check-license/check-license.go

API changes for https://github.com/cs3org/reva/issues/2001#issuecomment-915090968
blocked by https://github.com/cs3org/cs3apis-build/pull/14
with the cs3apis-build PR I was able to build the protobuf and go with:
```
docker run -v /path/to/cs3apis:/root/cs3apis -v /path/to/cs3apis-build/cs3apis-build:/usr/local/bin/cs3apis-build cs3org/cs3apis cs3apis-build -build-proto
docker run -v /path/to/cs3apis:/root/cs3apis -v /path/to/cs3apis-build/cs3apis-build:/usr/local/bin/cs3apis-build cs3org/cs3apis cs3apis-build -build-go
```
See https://github.com/cs3org/go-cs3apis/pull/44

try to use the google protobuf field mask

---

cs3/app/registry/v1beta1/resources.proto
docs/index.html

needed by https://github.com/cs3org/reva/pull/2230

add default_application to MimeTypeInfo

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/storage/provider/v1beta1/provider_api.proto
docs/index.html

~`CreateFile`~ `TouchFile` can be used to create an empty file. This is the file counterpart of `CreateContainer`. It allows one to easily create a file in order to reference it with a storage and opaque id. (Referencing it with a path or a relative path is already possible without the existing file).
One could use the `InitiateFileUpload` in order to upload a zero byte file. it will give you an array of upload methods (eg. TUS and simple) and you can then invoke the upload of the zero byte file.
This means you need an http request ( in case of the simple protocol ) in addition to the InitiateFileUpload grpc request.
To spare that http request, some file system implementations, eg the decomposedfs implement a shortcut (https://github.com/cs3org/reva/blob/4879bf6be97aecc9e30ad999355342b6ca6 …

add TouchFile

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/storage/provider/v1beta1/provider_api.proto
cs3/storage/provider/v1beta1/resources.proto
docs/index.html

As recently discussed, this is a minimal API that would initially be used by the WOPI server to manage its locks.
The idea is to implement the `SHARED` lock type only for now, as that's the closest to the current WOPI server implementation. At a later stage, the `WRITE` lock (enforced by sync/webdav clients) would be more appropriate for the WOPI server.
Fixes #6. At least strives to ;-) (and comments are welcome to have as complete an API as possible)

Adding support for a Lock API

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/permissions/v1beta1/permissions_api.proto
cs3/permissions/v1beta1/resources.proto
docs/index.html

This is the proposed CS3 API extension to introduce a permissions service.
Currently this API is read-only but eventually should also allow to set or update permissions / assignments.

first prototype for the permissions service api

---

cs3/storage/provider/v1beta1/provider_api.proto
cs3/storage/provider/v1beta1/resources.proto

@glpatcern @wkloucek Setting just an mtime does not tell the server when it can release the lock. I propose we use a Timestamp to store the expiration timestamp instead. This would also align better with the WebDAV `Timeout` request header for the LOCK method: http://www.webdav.org/specs/rfc2518.html#rfc.section.9.8
It also allows setting the 30min WOPI timeout, documented as MUST by https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/concepts#lock and https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/files/refreshlock

Rework Lock API metadata and add missing argument to Unlock

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/tx/v1beta1/resources.proto
cs3/tx/v1beta1/tx_api.proto
docs/index.html
proto.lock

Functionality for data transfer based on pull model.

Data transfer pull model

---

cs3/auth/registry/v1beta1/registry_api.proto
docs/index.html
proto.lock

In reva, we support basic auth through various mechanisms. One could be the simple auth provider which connects to an LDAP backend, but at the same time, we have the application auth service which is used to create temporary passwords with restricted scope. Both the services need to be enabled simultaneously and should be considered for a request trying to authenticate via basic auth. This PR enables that.

Match multiple providers in auth registry

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/storage/provider/v1beta1/provider_api.proto
docs/index.html

Follow up of cs3org/cs3apis#162: the storage methods that modify a resource now have an optional `lock_id` argument, such that storage provider implementations can enforce the lock validation.
In addition, also the `InitiateDownloadRequest` has this extra argument, in order to honor exclusive locks. The assumption then is that stat and metadata read operations are always allowed (when access rights are met), such that e.g. the web UI can show users that "File important_stuff.txt is locked in exclusive mode by user bob".

Add an optional lock_id argument to storage methods

---

cs3/storage/provider/v1beta1/resources.proto
docs/index.html

As discussed in https://github.com/cs3org/reva/issues/1804#issuecomment-1076471437 this PR introduces a `parent_id` property in `ResourceInfo`.
The property is added as `OPTIONAL`, both to not introduce a breaking change and to keep compatibility with the case of absolute paths, where it is actually not needed.
@butonic and @wkloucek, do you agree on the spec? including the fact that for single-file shares it `MUST` be set to `0`?

Added parent_id reference to ResourceInfo

---

cs3/preferences/v1beta1/preferences_api.proto
cs3/preferences/v1beta1/resources.proto
docs/index.html
proto.lock

The various user preferences can belong to various namespaces, for example, core, files, apps. This PR adds the required config for that.

Add namespace config to user preferences calls

---

cs3/sharing/link/v1beta1/resources.proto

`quicklink` is a simple bool value that indicates a unique link. The server will enforce that there is at max 1 quicklink per resource. This way the client can be sure there are not more than 1 quicklink and can adjust its UI.

Add quicklink field to link resource

---

cs3/storage/provider/v1beta1/resources.proto
docs/index.html

The `Creator` is needed for grants, because creator may have special permissions when editing the grant

Add creator to grant

---

cs3/sharing/collaboration/v1beta1/collaboration_api.proto
cs3/sharing/link/v1beta1/link_api.proto
cs3/sharing/ocm/v1beta1/ocm_api.proto
cs3/storage/provider/v1beta1/provider_api.proto
cs3/storage/provider/v1beta1/resources.proto
docs/index.html

Releated to https://github.com/cs3org/reva/issues/2976
to improve the performance.
@labkode

Performance improvements

---

cs3/storage/provider/v1beta1/resources.proto
docs/index.html

To correctly address storage spaces in reva, we need another id property on the resourceID.
This change is not breaking and should be compatible for the `master` and the `edge` branches.
1) `master`branch.
We do not need to change anything
2) `edge` branch
Currently the `storageID` attribute is used for a concatenated `<storageproviderID>$<spaceID>`
With this change, we will be able to separate them and have a clean implementation back.
@labkode @glpatcern I will also update the cs3apis on the master branch to keep everything on the same version of the apis.

add spaceID to resourceID

---

cs3/storage/provider/v1beta1/resources.proto
docs/index.html

This change adds an optional `expiration` field to `FileUploadProtocol` which can be used to indicate how long an upload to that resource will be possible.

Add an expiration to FileUploadProtocol

---

cs3/storage/provider/v1beta1/provider_api.proto
docs/index.html

This change adds an optional `if_unmodified_since` field to InitiateFileUploadRequest which allows for conditional uploads based on the mtime.

Add a if_unmodified_since condition to InitiateFileUploadRequest

---

cs3/app/provider/v1beta1/provider_api.proto
docs/index.html

This mini PR adds a new option for the `OpenInApp` endpoint.
The use-case for it is to provide a non-editable preview of documents to users in certain cases (typically, single-file shares / public links), yet having the ability to switch to edit mode if underlying permissions allow editing.
The current AppProvider's WOPI driver would fully delegate this to the WOPI server. Only the web frontend would need to have some `preview` action implemented, cc @wkloucek @diocas.

Added PREVIEW as an additional ViewMode for apps

---

cs3/sharing/link/v1beta1/link_api.proto
cs3/sharing/link/v1beta1/resources.proto

Added a description to public shares, so an user can describe the scope of the share.

Add description to public share

---

cs3/sharing/link/v1beta1/link_api.proto
docs/index.html

This PR adds a new flag `internal` when creating a public link, indicating that it will be used for internal purposes only, like from applications, and not showed in the ListPublicShares.

Allow a public share to be used internally

---

cs3/sharing/collaboration/v1beta1/resources.proto
docs/index.html

Added share filters to filter shares by space id and by state
The space id filter is already being used in the Reva edge branch [1] but we never properly introduced it to the API and the state filter is a new change [2].
[1] https://github.com/cs3org/reva/blob/edge/pkg/share/share.go#L122-L131
[2] https://github.com/owncloud/ocis/issues/3843

add more share filters

---

cs3/identity/user/v1beta1/resources.proto

When accessing public shares in a project space (which has no owner, only managers) we need to be able to pass a userid through the system which permission checks can work with.
Another use case is when trying to index a space on behalf of the space owner.
In both cases the user id MUST be set to the space id to reflect which space is supposed to be indexed.
Signed-off-by: Jörn Friedrich Dreyer <jfd@butonic.de>

add new user type space owner

---

cs3/ocm/invite/v1beta1/invite_api.proto
docs/index.html

https://github.com/cs3org/OCM-API/pull/54 requires that when accepting an invitation token, also the initiator's info are exchanged back.
This PR adds this info in the AcceptInvite response.

Get initiator's info on AcceptInvite

---

cs3/ocm/invite/v1beta1/invite_api.proto

An invitation token has an optional field `description` that currently is not possible to set.
This PR adds an optional `description` field when generating an invitation token.

Add description when generating an invitation token

---

cs3/ocm/invite/v1beta1/invite_api.proto
docs/index.html

This PR adds all the error code that the InviteAPIs must return.

Add error codes to InviteAPIs

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/tx/v1beta1/tx_api.proto
docs/index.html
proto.lock

Deals with https://github.com/cs3org/cs3apis/issues/189
This is a breaking change.

Name change in module datatx: PullTransfer -> CreateTransfer

---

cs3/ocm/core/v1beta1/ocm_core_api.proto
cs3/sharing/ocm/v1beta1/ocm_api.proto
cs3/sharing/ocm/v1beta1/resources.proto
docs/index.html

Following the discussions in https://github.com/cs3org/OCM-API/issues/66, this is to prepare the CS3APIs so that we clarify how the OCM properties `protocol`, `providerId` are actually represented by the more appropriate naming `protocols`, `shareId`, already introduced in previous PRs.
Therefore this change is purely on comments. The implementation will follow in Reva.

[docs-only] added comments to detail the mapping of OCM properties

---

cs3/storage/provider/v1beta1/provider_api.proto

See https://github.com/cs3org/reva/pull/2120
Maybe we want to change this in a next (breaking) version of CS3 APIs but for now I think it's beneficial to at least let the comments reflect how reva behaves, right?

[docs-only] Add code comments to RestoreRecycleItemRequest

---

cs3/sharing/link/v1beta1/link_api.proto
cs3/sharing/link/v1beta1/resources.proto
docs/index.html

This PR adds two fields to the public link share API, in the context of the [new notification service in the backend](https://github.com/cernbox/reva/pull/43).
`notify_uploads` stores wheter the uploads to a public link will be notified to the owner, and `notify_uploads_extra_recipients` contains a comma-separated list of extra email addresses to notify too.

Notifications

---

cs3/sharing/ocm/v1beta1/resources.proto
proto.lock

The OCM APIs specify a `providerId` field that is a remote share id, and not a unique identifier in the provider of the resource.
This PR adapt the CS3APIs to this semantic.

Send remote share id on OCM share create

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/rpc/v1beta1/code.proto
cs3/sharing/collaboration/v1beta1/collaboration_api.proto
docs/index.html

This adds: CODE_LOCKED to the rpc codes
The ability to lock a resource is specific to some WebDAV servers. 
The HTTP 423 Locked error response code indicates that either the resources tentatively targeted by is locked, meaning it can't be accessed. 
HTTP Mapping: 423 Locked

the code locked has been added

---

cs3/app/provider/v1beta1/resources.proto
cs3/app/registry/v1beta1/resources.proto
docs/index.html

Also added `action` to AppProviderInfo.
The exercise here is to demonstrate a different kind of integration, where the app lives on an external cloud and uses its own login and storage. Therefore it can't be embedded in an iframe and the integration is more loose, with the user driving the `Export to` and `Import from` actions as opposed to a simple `Open with`.

Added target to OpenInAppURL object

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/storage/provider/v1beta1/provider_api.proto
cs3/storage/provider/v1beta1/spaces_api.proto
proto.lock

The spaces API are currently coupled with the storage. This PR decouple them from the storage, allowing a more flexible implementation.

Decouple spaces API from storage

---

cs3/rpc/v1beta1/status.proto

Sometimes, the RPC status & message combination is not sufficient to transport more details to the clients.
Therefore, an optional innerError is added to the Status object.
After discussing this with @butonic, we think this is the correct place because that bundles all application logic in one place and keeps it separate from the transport.

add inner error to rpc status

---

cs3/storage/provider/v1beta1/provider_api.proto

The rationale of this PR is that an `InitiateFileUpload` request shall only provide an endpoint, for the client to perform the upload as a separate step. Therefore, any lock validation MUST be performed again at the actual upload time, when the `lock_id` is to be passed again, and as such there's no need to include it in the payload of InitiateFileUplod.
How is Reva/edge dealing with _atomically_ ensuring the lock is valid currently? @wkloucek and/or @micbar can you shed some light? My only guess is that you'd validate the lock again during the TUS upload. In that case, we may just shortcut.
For Reva/master, this is in the makings (at relatively low priority), that's why I realized only now about this.

Clarified scope of lock_id in InitiateFileUploadRequest

---

cs3/storage/provider/v1beta1/provider_api.proto

Follow up from #226: the `lock_id` payload of storage requests that do not alter the content of a file MAY or MAY NOT be honored, because the storage MAY allow for modifying files' metadata (in particular grants or other arbitrary metadata) without enforcing eventual locks.
As such, the spec changed from `MUST` to `SHOULD`, with an additional `MAY` clause.
This only affects the comments, the protobuf payloads did not change.

Further clarified scope of lock_id

---

cs3/gateway/v1beta1/gateway_api.proto
cs3/gateway/v1beta1/resources.proto
cs3/sharing/link/v1beta1/resources.proto

This is a breaking change as the recently added `ListExistingReceivedShares` has been redefined to make it more clear to use.
In addition, methods for `ListExistingShares` and `ListExistingPublicShares` have been added, following the same principle.

Add calls for listing all types of shares and include storage resource info

---

.github/workflows/build-and-publish.yml

See https://github.com/cs3org/go-cs3apis/issues/57

Added mockery step in CI pipeline to automatically generate mocked interfaces for the Go target

---

.github/workflows/build-and-publish.yml

The current pipeline has a bit of code that generates mock files based on the defined interfaces, and then automatically commits them:
```
mockery
git add .
git commit -m 'Generated mock interfaces for https://github.com/cern-eos/grpc-proto/tree/${{ github.sha }}'
git push origin main
```
This makes the pipeline fail, because `git commit` will return a non-zero exit code when there is nothing to commit. This PR solves this issue.

Updated build pipeline to not fail when there are no changes in the generated mocks

---

cs3/ocm/provider/v1beta1/resources.proto
cs3/storage/provider/v1beta1/provider_api.proto

`TouchFile` MAY also need the `lock_id` in some storage providers. See https://github.com/cs3org/wopiserver/pull/142#issuecomment-1898138468 for a case where it was missing.

Add lock to TouchFile + minor comments

---

cs3/app/registry/v1beta1/resources.proto

app provider: make the new product_name field required

---

cs3/sharing/collaboration/v1beta1/resources.proto

This PR introduces two extra properties to shares:
* A `description` that the owner of a share can set when creating the share
* An `alias` each recipient of a share can set, to enable them renaming it in their "shared with me" view

RFE: add Share.description and ReceivedShare.alias

---

cs3/ocm/core/v1beta1/ocm_core_api.proto
cs3/ocm/invite/v1beta1/invite_api.proto
cs3/sharing/ocm/v1beta1/resources.proto

This PR includes the necessary changes in order to accommodate the new properties in OCM 1.2.
The only breaking change is with the `webapp` protocol payload, as `uri_template` has been renamed `uri`. But "to the best of our knowledge" only Reva master implements apps sharing and will be adapted. Other Reva implementations would remain compatible.

Adapted OCM payloads to OCM 1.2

---

cs3/storage/provider/v1beta1/resources.proto

This PR adds an aditional bool flag to the drive item called `hasTrashItems` this is used to show whether there are items in the drives trashbin or not.  
With that little change, everybody will be able to implement a cost-efficient way to query whether a storage provider has trashed items, without having to read the whole trashbin. (our current implementation can be reviewed here for decomposedfs and posixfs: https://github.com/opencloud-eu/reva/pull/268/files)

add hasTrashedItems property to drive object

---

cs3/identity/user/v1beta1/resources.proto

This pull request introduces an optional `tenant_id` field to `UserId`, which allows for identifying the tenant of the corresponding user.

Add a tenant_id to UserIds

---

cs3/identity/group/v1beta1/resources.proto

This is in preparation for future "federated" groups, in particular looking after OCM-based federations.
Also this prepares a change similar to #247, which would be a breaking change for uniformity, where group filters are called `query`. @micbar I guess this specific PR is OK, and without further comments we will go ahead also for that.

Added support for federated groups + added comments
